name: Genesis Backend Setup with Firebase

on:
  push:
    branches:
      - AuraOS
  workflow_dispatch:

jobs:
  setup-genesis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r app/ai_backend/requirements.txt

      - name: Make Google services file available
        run: |
          echo "Using google-services.json from app folder"
          ls app/google-services.json

      - name: Run Genesis startup script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/app/google-services.json
        run: |
          bash app/ai_backend/start_genesis.sh
