name: Android CI

on:
  push:
    branches: [ AuraOS ]
  pull_request:
    branches: [ AuraOS ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24 (OpenJDK/Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '36'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # --------- PREBUILD & GENERATION STEPS ---------
      - name: Run Prebuild Tasks
        run: ./gradlew prebuild # <-- Replace with your actual prebuild command

      - name: Generate OpenAPI files for main
        run: ./gradlew :app:generateOpenApiDocs # <-- Replace with your actual task

      - name: Generate OpenAPI files for buildSrc
        run: ./gradlew :buildSrc:generateOpenApiDocs # <-- Replace with your actual task

      # --------- LPOSED & AI BACKEND SETUP ---------
      - name: Setup Lposed module
        if: exists('./scripts/setup-lposed.sh')
        run: ./scripts/setup-lposed.sh # <-- Replace with your actual Lposed setup script

      - name: Setup AI backend
        if: exists('./scripts/setup-ai-backend.sh')
        run: ./scripts/setup-ai-backend.sh # <-- Replace with your actual AI backend setup script

      # --------- FINAL BUILD & ARTIFACTS ---------
      - name: Build all modules (Release)
        run: ./gradlew assembleRelease

      - name: Upload APK/AAB artifacts from all modules
        uses: actions/upload-artifact@v4
        with:
          name: AppBuilds
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab
